# Generated by Django 4.1.6 on 2023-04-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('contraseñaCON', models.CharField(max_length=50)),
            ],
        ),
    ]
