# Generated by Django 4.1.6 on 2023-04-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Telefono',
            field=models.IntegerField(),
        ),
    ]
